blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, VersionCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('new/', BlogCreateView.as_view(), name='new'),
    path('blog', BlogListView.as_view(), name='blog'),
    path('view/<slug:slug>/',  cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('edit/<slug:slug>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete'),
    path('new_ver/', VersionCreateView.as_view(), name='new_ver')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('users.urls', namespace='user')),
]

blog/models.py
from django.db import models

from users.models import User


class Blog(models.Model):
    blog_title = models.CharField(max_length=200, verbose_name='название')
    content = models.TextField(verbose_name='содержимое')
    image = models.ImageField(verbose_name='изображение', null=True, blank=True)
    created_at = models.DateTimeField(verbose_name='дата создания', null=True, blank=True, auto_now_add=True)
    views_count = models.IntegerField(default=0, verbose_name='просмотров')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор', null=True, blank=True)

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'публикации'
        permissions = [
            (
                'can_published',
                'Может публиковать посты (кастомное)'
            )
        ]



    def __str__(self):
        return f'Публикация \"{self.blog_title}\"'


class Version(models.Model):
    version_title = models.CharField(max_length=200, verbose_name='название')
    product = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='продукт', related_name='versions')
    version_number = models.IntegerField(default=0, verbose_name='номер версии')
    is_current = models.BooleanField(default=True, verbose_name='текущая версия')

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

    def __str__(self):
        return f'Версия №{self.version_number}, \"{self.version_title}\"'

blog/forms.py
from django import forms

from blog.models import Blog, Version


class PostForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('blog_title', 'content', 'is_published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            from django.forms import CheckboxInput
            if isinstance(field.widget, CheckboxInput):

                field.widget.attrs['class'] = 'form-check'

            else:
                field.widget.attrs['class'] = 'form-control'

    def cleaning(self, models_field):
        # Вспомогательный метод для валидатора. Он делает всю работу.

        exception_words = ['казино', 'криптовалюта', 'крипта', 'биржа',
                           'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        cleaned_data = self.cleaned_data.get(models_field)

        for exc_word in exception_words:
            if exc_word in cleaned_data or exc_word.capitalize() in cleaned_data or exc_word.upper() in cleaned_data:
                raise forms.ValidationError('Использовано запрещённое слово')

        return cleaned_data

    def clean_blog_title(self):
        # валидатор просто передаёт имя нужного поля
        return self.cleaning('blog_title')

    def clean_content(self):
        # валидатор просто передаёт имя нужного поля

        return self.cleaning('content')


class VersionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            from django.forms import CheckboxInput
            if isinstance(field.widget, CheckboxInput):

                field.widget.attrs['class'] = 'form-check'

            else:
                field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Version
        fields = ('version_title', 'product', 'version_number', 'is_current')


class PostFormForModerator(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('blog_title', 'content', 'is_published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            from django.forms import CheckboxInput
            if isinstance(field.widget, CheckboxInput):
                field.widget.attrs['class'] = 'form-check'
            else:
                field.widget.attrs['class'] = 'form-control'
            if field_name in ('blog_title', 'content'):
                field.widget.attrs['readonly'] = True

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.utils.text import slugify

from blog.models import Blog, Version
from blog.forms import PostForm, VersionForm, PostFormForModerator


def rus_to_slug(rus_string):
    """
    Превращает текст в слаг, переводя русские буквы в транслит
    :param rus_string: текст для слагирования
    :return: слаг, готовый для вставки в url
    """

    rus_abc = ('абвгдеёжзийклмнопрстуфхцчшщьыъэюя')
    slug_abc = ('a', 'b', 'v', 'g', 'd', 'e', 'jo', 'zh', 'z', 'i',
                'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'f',
                'h', 'c', 'ch', 'sh', 'sch', '', 'y', '', 'e', 'ju', 'ja')
    trance_table = {}
    for num in range(len(rus_abc)):
        letter = rus_abc[num]
        trance_table[ord(letter)] = slug_abc[num]

    result = rus_string.lower().translate(trance_table)

    return slugify(result)


class FormValidMixin():
    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            slug = rus_to_slug(new_post.blog_title)
            for blog in Blog.objects.all():
                if slug == rus_to_slug(blog.blog_title):
                    new_post.slug = slug + 'a'
                    break
            else:
                new_post.slug = slug
            new_post.save()
        return super().form_valid(form)


class BlogCreateView(FormValidMixin, LoginRequiredMixin, CreateView):
    model = Blog
    form_class = PostForm
    success_url = reverse_lazy("blog:blog")



    extra_context = {
        'some_text': "Какой-то текст для страницы добавления нового поста",
        'title': "Новый пост"
    }

    # def get_success_url(self):
    #     return reverse('blog:view', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        new_post = form.save()
        new_post.author = self.request.user
        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    extra_context = {
        'some_text': "Какой-то текст для страницы просмотра постов",
        'title': "Наш блог"
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if self.request.user.is_staff or self.request.user.has_perm('blog.can_published'):
            return queryset
        return queryset.filter(is_published=True)



class BlogDetailView(DetailView):
    model = Blog
    extra_context = {
        'some_text': "Какой-то текст для страницы просмотра поста",
        'title': "Просмотр поста"
    }

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(FormValidMixin, LoginRequiredMixin, UpdateView):
    template_name = 'blog/blog_update.html'
    model = Blog
    form_class = PostForm
    # success_url = reverse_lazy("blog:blog")
    extra_context = {
        'some_text': "Какой-то текст для страницы изменения постов",
        'title': f"Отредактировать пост"
    }

    def get_form_class(self):
        if self.request.user.has_perm('blog.can_published') and self.request.user != self.object.author:
            return PostFormForModerator
        return self.form_class

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        VersionFormset = inlineformset_factory(Blog, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']

        if formset.is_valid():
            formset.instance = form.save()
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.object.slug])


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog")
    extra_context = {
        'some_text': "Какой-то текст для страницы удаления постов",
        'title': f"Удаляем пост "
    }


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy("blog:blog")

    extra_context = {
        'some_text': "Какой-то текст для страницы добавления новой версии",
        'title': "Новая версия"
    }

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="card card-sm col-6 mx-auto">
    <div class="card-body d-flex justify-content-between">
        <p class="  m-0">{{object.blog_title}}</p>
    </div>
    <div class="card-footer d-flex justify-content-between">
        <p class="h6 m-0">{{object.content}}</p>
    </div>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a class="p-2 btn " href={% url 'blog:blog' %}>Отмена</a>
    </form>

</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="card card-s mx-auto">
    <div class="card-header d-flex justify-content-between h6">
        <p class="  m-0">{{object.blog_title }}</p>
    </div>
    <div class="card-body d-flex justify-content-between">
        <p class=" m-0">{{object.content}}</p>
    </div>
    <div class="card-body d-flex justify-content-between">
        <p class=" m-0">Автор: {{object.author}}</p>
    </div>
    <div class="card-footer d-flex justify-content-end">
        <a href={% url 'blog:new_ver' %} class="m-0 mx-left">Создать версию</a>
    </div>
    <div class="card-footer d-flex justify-content-end">
        <p class="m-0 mx-left">Создано: {{ object.created_at }} Просмотров: {{ object.views_count }}</p>
    </div>
    <div class="card-footer d-flex justify-content-center">
                {% if object.author == user or user.is_staff or perms.blog.can_published %}
                    <a class="p-2 btn btn-info" href={% url 'blog:edit' object.slug %}>Изменить</a>
                    <a class="p-2 btn btn-warning" href={% url 'blog:delete' object.slug %}>Удалить</a>
                {% endif %}
    </div>
    <div class="card-footer d-flex justify-content-between">
        {% if object.versions.exists %}
            {% for vers in object.versions.all %}
                {% if vers.is_current %}
                    <p class="m-0">{{ vers.version_title}}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-6 mx-auto">
    <form xmlns="http://www.w3.org/1999/html" method="post">
      {% csrf_token %}
      {{form.as_p}}

      <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}

<ul class="row list-unstyled justify-content-center">
    {% for object in object_list %}
    <li class="col-5 mb-3">
        <div class="card card-sm">
            <div class="card-header d-flex justify-content-between">
                <p class=" h6  m-0">{{object.blog_title|truncatechars:70}}</p>
            </div>
            <div class="card-body d-flex justify-content-between">
                <p class="m-0">{{object.content|truncatechars:300}}</p>
            </div>
            <div class="card-footer d-flex justify-content-center">
                <a class="p-2 btn btn-success" href={% url 'blog:view' object.slug %}>Открыть</a>
                {% if object.author == user or user.is_staff or perms.blog.can_published %}
                    <a class="p-2 btn btn-info" href={% url 'blog:edit' object.slug %}>Изменить</a>
                    <a class="p-2 btn btn-warning" href={% url 'blog:delete' object.slug %}>Удалить</a>
                {% endif %}
            </div>
            <div class="card-footer d-flex justify-content-between">
                {% if object.versions.exists %}
                    {% for vers in object.versions.all %}
                        {% if vers.is_current %}
                            <p class="m-0">{{ vers.version_title}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <p class="m-0 ">Просмотров: {{object.views_count}}</p>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

{% endblock %}

blog/templates/blog/blog_update.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div >
            <form class=" d-flex" xmlns="http://www.w3.org/1999/html" method="post">
                <div class="flex-grow-1 ms-5">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
                <div class="flex-grow-1  ms-5">
                    {{ formset.management_form}}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% endfor %}
                </div>
            </form>
        </div>
        {% endblock %}