blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, VersionCreateView

app_name = BlogConfig.name

urlpatterns = [
    path('new/', BlogCreateView.as_view(), name='new'),
    path('blog', BlogListView.as_view(), name='blog'),
    path('view/<slug:slug>/',  cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('edit/<slug:slug>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete'),
    path('new_ver/', VersionCreateView.as_view(), name='new_ver')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import index, contacts, ProductListView, ProductCreateView, ProductDetailView, ProductUpdateView, \
    ProductDeleteView, CategoryCreateView

app_name = CatalogConfig.name

urlpatterns = [
                  path('', index, name='index'),
                  path('contacts', contacts, name='contacts'),
                  path('catalog', ProductListView.as_view(), name='catalog'),
                  path('new/', ProductCreateView.as_view(), name='new'),
                  path('view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view'),
                  path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
                  path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
                  path('new_ver/', CategoryCreateView.as_view(), name='new_category')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('users.urls', namespace='user')),
]

catalog/models.py
from django.db import models
from django.utils import timezone, text

from users.models import User


# Create your models here.


class Product(models.Model):
    product_name = models.CharField(max_length=120, verbose_name='Название')
    product_description = models.CharField(max_length=600, verbose_name='Описание')
    image = models.ImageField(upload_to='images/', verbose_name='Изображение', null=True, blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    created_at = models.DateTimeField(verbose_name='Создано', default=timezone.now)
    changed_at = models.DateTimeField(verbose_name='Изменено', default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор', null=True, blank=True)
    is_active = models.BooleanField(default=True, verbose_name='опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True, blank=True)

    def __str__(self):
        return self.product_name


class Category(models.Model):
    category_name = models.CharField(max_length=120, verbose_name='Название')
    category_description = models.TextField(max_length=600, verbose_name='Описание')
    created_at = models.DateTimeField(verbose_name='Создано', default=timezone.now)

    def __str__(self):
        return self.category_name

catalog/forms.py
from django import forms

from catalog.models import Product, Category


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_name', 'product_description', 'category', 'image', 'price', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            from django.forms import CheckboxInput
            if isinstance(field.widget, CheckboxInput):

                field.widget.attrs['class'] = 'form-check'

            else:
                field.widget.attrs['class'] = 'form-control'


class CategoryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            from django.forms import CheckboxInput
            if isinstance(field.widget, CheckboxInput):

                field.widget.attrs['class'] = 'form-check'

            else:
                field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Category
        fields = ('category_name', 'category_description')

catalog/views.py
from django.shortcuts import render

from catalog.forms import ProductForm, CategoryForm
from catalog.models import Product, Category
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:catalog")

    extra_context = {
        'some_text': "Какой-то текст для страницы добавления нового продукта",
        'title': "Новый продукт"
    }

    def form_valid(self, form):
        new_product = form.save()
        new_product.author = self.request.user
        return super().form_valid(form)


class ProductDetailView(DetailView):
    model = Product
    extra_context = {
        'some_text': "Какой-то текст для страницы просмотра поста",
        'title': "Просмотр поста"
    }


class ProductListView(ListView):
    model = Product
    extra_context = {
        'some_text': "Какой-то текст для страницы товаров",
        'title': "Товары"
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if self.request.user.is_staff:
            return queryset
        return queryset.filter(is_active=True)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    extra_context = {
        'some_text': "Какой-то текст для страницы изменения продукта",
        'title': "Отредактировать продукт"
    }


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:catalog")
    extra_context = {
        'some_text': "Какой-то текст для страницы удаления постов",
        'title': f"Удаляем пост "
    }



def index(request):
    context = {
        'some_text': "Какой-то текст для главной страницы",
        'title': "Главная"
    }

    return render(request, 'catalog/index.html', context)


def contacts(request):
    context = {
        'some_text': "Какой-то текст для страницы контактов",
        'title': "Контакты"
    }

    return render(request, 'catalog/contacts.html', context)


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy("catalog:catalog")

    extra_context = {
        'some_text': "Какой-то текст для страницы добавления новой категории",
        'title': "Новая категория"
    }

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<h5 class="my-0 mr-md-auto font-weight-normal">Магазинчик</h5>
    {% include 'catalog/includes/inc_main_menu.html'%}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ title }}</h1>
        {% block content %}
        {% endblock %}
    </div>
    <div class="container">
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                        {{ title }}<br>
                        {{ some_text }}
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>

                <div class="col-6 col-md">
{% include 'catalog/includes/inc_main_menu.html'%}
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

catalog/templates/catalog/category_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6 mx-auto">
    <form xmlns="http://www.w3.org/1999/html" method="post">
      {% csrf_token %}
      {{form.as_p}}


      <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}

    <p class="lead">Контакты</p>

{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content %}

    <p class="lead">Просто главная страница</p>

{% endblock %}

catalog/templates/catalog/items.html
{% extends 'catalog/base.html' %}
{% load my_tags %}


{% block content %}


            <p class="lead">Страница товаров</p>
            <ul class="row list-unstyled justify-content-center">
                {% for object in object_list %}
                <li class="col-5 mb-3">
                    <div class="card card-sm">
                        <img class="card-img-top" src={{object.image|mediapath}}  alt="Здесь могла быть ваша реклама">
                        <div class="card-body d-flex justify-content-between">
                          <p class="  m-0">{{object.product_description}}</p>
                        </div>
                        <div class="card-footer d-flex justify-content-between">
                          <p class="h6 m-0">{{object}}</p>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="card card-sm col-6 mx-auto">
    <div class="card-body d-flex justify-content-between">
        <p class="  m-0">{{object.product_name}}</p>
    </div>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
        <a class="p-2 btn " href={% url 'catalog:catalog' %}>Отмена</a>
    </form>

</div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="card card-s mx-auto">
    <div class="card-header d-flex justify-content-between h6">
        <p class="  m-0">{{object.product_name }}</p>
    </div>
    <div class="card-body d-flex justify-content-between">
        <p class=" m-0">{{object.product_description}}</p>
    </div>
    <div class="card-body d-flex justify-content-between">
        <p class=" m-0">Автор: {{object.author}}</p>
    </div>
    <div class="card-footer d-flex justify-content-center">
        {% if object.author == user or user.is_staff %}
        <a class="p-2 btn btn-info" href={% url 'catalog:edit' object.slug %}>Изменить</a>
        <a class="p-2 btn btn-warning" href={% url 'catalog:delete' object.slug %}>Удалить</a>
        {% endif %}
    </div>
    <div class="card-footer d-flex justify-content-between">
        {% if object.category.exists %}
        <p class="m-0">{{ object.category.category_name}}</p>
        {% endif %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-6 mx-auto">
    <form xmlns="http://www.w3.org/1999/html" method="post">
      {% csrf_token %}
      {{form.as_p}}

      <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}


{% block content %}

            <a  href={% url 'catalog:new_category' %}>Создать категорию товаров
            </a>

            <p class="lead">Страница товаров</p>
            <ul class="row list-unstyled justify-content-center">
                {% for object in object_list %}
                <li class="col-5 mb-3">
                    <div class="card card-sm">
                        {% if object.image.exists %}
                        <img class="card-img-top" src={{object.image|mediapath}}  alt="Здесь могла быть ваша реклама">
                        {% else %}
                        <img class="card-img-top" src="{{ MEDIA_URL }}images/Designer.jpeg"  alt="Здесь могла быть ваша реклама">
                        {% endif %}
                        <div class="card-body d-flex justify-content-between">
                          <p class="  m-0">{{object.product_description}}</p>
                        </div>
                        <div class="card-footer d-flex justify-content-between">
                          <p class="h6 m-0">{{object}}</p>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
{% endblock %}

catalog/templates/catalog/product_update.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div >
            <form class=" d-flex" xmlns="http://www.w3.org/1999/html" method="post">
                <div class="flex-grow-1 ms-5">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            </form>
        </div>
        {% endblock %}

catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-6 mx-auto">
    <form xmlns="http://www.w3.org/1999/html" method="post">
      {% csrf_token %}
      {{form.as_p}}


      <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}